### ISSUE TITLE
Invalid file extension

### ISSUE THREAD

**Issue by lutzroeder** [AlexHJH/onnx_text#1]
[AlexHJH](https://github.com/AlexHJH) `.onnxtxt` should not be used as an extension for ONNX textual syntax as it will conflict with other files [using](https://github.com/search?q=extension%3Aonnxtxt&type=Code) the Protocol Buffers text format. Can you please clarify what the correct extension for these files should be.

**Comment by AlexHJH** [comment]
since onnx has not defined any extension for these files written by the new textual syntax yet. i shall make the extension to be `.onnx.txt` conservatively,and now the test file changed. @lutzroeder

**Comment by AlexHJH** [comment]
maybe  `.onntxt` a better choice

**Comment by lutzroeder** [comment]
@AlexHJH which might be used for Protocol Buffers text format as well. This might be more of a design or goal discussion to have with the ONNX team. If this is not a supported scenario, maybe model files in this format should not exist right now?

**Comment by AlexHJH** [comment]
of course, these is no official description of the future development for this syntax.but this feature does greatly help developers to modify or create their onnx model flexibly instead of writing code . i will  pay close attention for it

**Comment by AlexHJH** [comment]
@lutzroeder of course, these is no official description of the future development for this syntax.but this feature does greatly help developers to modify or create their onnx model flexibly instead of writing code . i will pay close attention for it
